### ISSUE TITLE
Windows sample practice

### ISSUE THREAD

**Issue by ksyang00** [aws-samples/aws-ecs-devops-using-aws-cdk#1]
Do you have any practice samples for windows?
Please let me know how I can do these practices on windows 10.

**Comment by kwonyulchoi** [comment]
Thank you for your attention.

I think that windows-based environment is not different from linux/mac.

Just difference is only environment setup.

For setting up CDK, please refer to the following link.

---> https://cdkworkshop.com/15-prerequisites.html

Thanks
